permalink: /:categories/:title.html
url: "http://pasindud.github.io/jekyll-masonry/"
full_name: "Your Full Name"
first_name: "Raihan's Photography"
last_name: "Portfolio"
blog_title: "Raihan's Portfolio"
author_img_name_path: "/images/users/user.png"
disqus_shortname: "bangladeshonmyown"
copyright_year: "2014"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Ghosteyes1"
github: "zwitteraihan"
facebook: "zwitterion.fritzwaggle"
linkined_url: ""
